Add healthcheck for divviup-api to compose.yaml
Adds a simple healthcheck on the `divviup-api` service in `compose.yaml`
that tickles the health endpoint. Also adds a check to the Docker CI job
that runs Docker compose and waits 120 seconds for it to become healthy.

Part of #1096

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -33,3 +33,16 @@ jobs:
           build-args: |
             GIT_REVISION=${{ steps.git.outputs.GIT_REVISION }}
             RUST_FEATURES=${{ matrix.rust-features }}
+      - name: Compose
+        id: compose
+        run: docker compose up --wait --waitfor 120
+        # continue on error so we can inspect containers in the next step
+        continue-on-error: true
+      - name: Inspect containers
+        if: steps.compose.outcome != 'success'
+        run: |
+          docker compose ps
+          for NAME in `docker compose ps --format json | jq -r '.Name'`; do
+            docker inspect $NAME
+          done
+          exit 1
